---
title: "Meme Dog Intelligence"
author: "Kesava"
date: 'Report Last Run: `r Sys.time()`'
output:
  pdf_document:
    toc_depth: 2
    number_sections: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load required packages
library("tidyverse")
library("data.world")
library("scales")
library("ggdogs") 
```

\centering
\raggedright
\newpage
\tableofcontents

\newpage

# Preface

Came across the ggdogs package and I wanted to plot something using the package. Here is my attempt using the data.world dataset of dog intelligence.

# Get data

```{r}
sql_stmt <- qry_sql("SELECT * FROM dog_intelligence")
query_results_df <- data.world::query(
  sql_stmt, "len/dog-size-intelligence-linked")
```

# Check

```{r}
query_results_df %>% head()
```


\newpage

# Get meme dogs data only

```{r}
breed_int <- c("Siberian Husky", "Chihuahua", "Pug", "Shiba Inu", "Pomeranian", 
               "Vizsla")
```

# Visualize

```{r fig.height=14, fig.width=14}
query_results_df %>% 
  filter(breed %in% breed_int) %>% 
  mutate(breed = fct_reorder(breed, desc(reps_lower))) %>%
  # ggplot(aes(obey, breed)) +
  ggplot(aes(x = obey, xend = 0, y = breed, yend = breed)) +
  geom_segment(size = 3, color = "yellow", alpha = 0.6) +
  # geom_point(aes(x = reps_lower)) +
  geom_point() +
  geom_dog(aes(x = 0.30, y = 1), dog = "chihuahua", size = 4) +
  geom_dog(aes(x = 0.30, y = 2), dog = "pug", size = 4) +
  geom_dog(aes(x = 0.50, y = 3), dog = "doge", size = 4) +
  geom_dog(aes(x = 0.50, y = 4), dog = "husky", size = 4) +
  geom_dog(aes(x = 0.85, y = 5), dog = "gabe", size = 4) +
  geom_dog(aes(x = 0.85, y = 6), dog = "hearing", size = 4) +
  scale_x_continuous(labels = percent_format(), 
                     breaks = seq(0,10, 0.1), 
                     limits = c(0, 1)) +
  labs(x = "\n Probability of Obeying to commands", 
       y = "", 
       title = "Meme dogs' intelligence",
       subtitle = "Pomeranians may obey you more than Huskies!",
       #title = "Siberian Husky is not as intelligent as a pomeranian!!"
       caption = "\n\n\n Visualisation by: Kesava Asam \n Data source: Data.World, Intelligence of Dogs by Len Fishman") +
  theme_minimal() +
  ggdark::dark_mode() +
  theme(plot.title = element_text(hjust = 0.5, family = "serif", size = 26),
        plot.subtitle = element_text(hjust = 0.5, size = 14),
        plot.caption = element_text(hjust = 0.5, size = 15, family = "serif"),
        axis.title.x = element_text(size = 15), 
        axis.text.x = element_text(size = 17),
        axis.text.y = element_text(size = 20)) 
```

```{r eval=FALSE, include=FALSE}
ggsave("data_world_dogs_intelligence_results_v1.jpeg", 
       plot = last_plot(), width = 300, height = 310, 
       units = "mm", dpi = 300)
```

\newpage

```{r}
sessionInfo()
```

